import {
  GraduationCap,
  Users,
  UserCheck,
  BookOpen,
  Compass,
  Shield,
  Layers,
  Phone,
} from 'lucide-react'
import { DIRECTORY_ENDPOINTS } from '../endpoints'

export const DIRECTORY_CATEGORIES = {
  lecturers: {
    key: 'lecturers',
    slug: 'lecturers',
    singular: 'Lecturer',
    plural: 'Lecturers',
    route: '/admin/directory/lecturers',
    endpoint: DIRECTORY_ENDPOINTS.lecturers,
    icon: GraduationCap,
    subnoteSuffix: 'active teaching',
    imageField: 'photo_url',
    hasConsultations: true,
    fields: [
      { name: 'photo_url', label: 'Profile Photo', type: 'image', colSpan: 2 },
      { name: 'name', label: 'Full Name', type: 'text', required: true, placeholder: 'e.g. Dr. Kwame Mensah' },
      { name: 'title', label: 'Title', type: 'select', options: ['Prof.', 'Assoc. Prof.', 'Dr.', 'Mr.', 'Mrs.', 'Ms.'] },
      { name: 'staff_id', label: 'Staff ID', type: 'text', placeholder: 'e.g. STF-8492' },
      { name: 'department_id', label: 'Department', type: 'department_select', required: true },
      { name: 'faculty', label: 'Faculty', type: 'text', placeholder: 'Faculty of Physical & Computational Sciences' },
      { name: 'specialization', label: 'Specialization', type: 'text', placeholder: 'e.g. Organic & Polymer Chemistry' },
      { name: 'qualification', label: 'Qualification', type: 'text', placeholder: 'e.g. Ph.D (Cambridge), M.Phil (Legon)' },
      { name: 'email', label: 'Email Address', type: 'email', placeholder: 'kmensah@ug.edu.gh' },
      { name: 'phone', label: 'Phone Number', type: 'text', placeholder: '+233 24 000 0000' },
      { name: 'office', label: 'Office Location', type: 'text', placeholder: 'Chem Block Rm 204' },
      { name: 'is_active', label: 'Status', type: 'boolean', default: true },
      { name: 'bio', label: 'Biography', type: 'textarea', colSpan: 2, placeholder: 'Short academic profile and research focus...' },
    ],
  },

  executives: {
    key: 'executives',
    slug: 'executives',
    singular: 'Executive',
    plural: 'Executives',
    route: '/admin/directory/executives',
    endpoint: DIRECTORY_ENDPOINTS.executives,
    icon: Users,
    subnoteSuffix: 'active cabinet',
    imageField: 'photo_url',
    fields: [
      { name: 'photo_url', label: 'Executive Photo', type: 'image', colSpan: 2 },
      { name: 'name', label: 'Full Name', type: 'text', required: true, placeholder: 'e.g. Abena Serwaa' },
      { name: 'position', label: 'Position', type: 'text', required: true, placeholder: 'e.g. President, Vice President, Secretary' },
      { name: 'student_id', label: 'Student ID', type: 'text', placeholder: '10984521' },
      { name: 'academic_year', label: 'Academic Year', type: 'text', required: true, placeholder: '2025/2026' },
      { name: 'department_id', label: 'Department', type: 'department_select', required: true },
      { name: 'level', label: 'Level', type: 'select', options: ['100', '200', '300', '400'] },
      { name: 'program', label: 'Program', type: 'text', placeholder: 'BSc Chemistry' },
      { name: 'email', label: 'Email', type: 'email', placeholder: 'aserwaa@st.ug.edu.gh' },
      { name: 'phone', label: 'Phone Number', type: 'text', placeholder: '+233 50 123 4567' },
      { name: 'display_order', label: 'Display Order', type: 'number', placeholder: '0 (higher displays first)' },
      { name: 'is_active', label: 'Status', type: 'boolean', default: true },
      { name: 'bio', label: 'Executive Bio', type: 'textarea', colSpan: 2, placeholder: 'Brief summary of role and responsibilities...' },
    ],
  },

  classRepresentatives: {
    key: 'classRepresentatives',
    slug: 'class-representatives',
    singular: 'Class Representative',
    plural: 'Class Representatives',
    route: '/admin/directory/class-representatives',
    endpoint: DIRECTORY_ENDPOINTS.classRepresentatives,
    icon: UserCheck,
    subnoteSuffix: 'active representatives',
    imageField: 'photo_url',
    fields: [
      { name: 'photo_url', label: 'Photo', type: 'image', colSpan: 2 },
      { name: 'name', label: 'Full Name', type: 'text', required: true, placeholder: 'e.g. Michael Ofori' },
      { name: 'student_id', label: 'Student ID', type: 'text', placeholder: '10912345' },
      { name: 'level', label: 'Level', type: 'select', required: true, options: ['100', '200', '300', '400'] },
      { name: 'class_name', label: 'Class / Stream', type: 'text', required: true, placeholder: 'e.g. Level 200 Chem A' },
      { name: 'program', label: 'Program', type: 'text', required: true, placeholder: 'BSc Chemistry' },
      { name: 'academic_year', label: 'Academic Year', type: 'text', required: true, placeholder: '2025/2026' },
      { name: 'department_id', label: 'Department', type: 'department_select', required: true },
      { name: 'email', label: 'Email', type: 'email', placeholder: 'mofori@st.ug.edu.gh' },
      { name: 'phone', label: 'Phone', type: 'text', placeholder: '+233 20 987 6543' },
      { name: 'is_active', label: 'Status', type: 'boolean', default: true },
    ],
  },

  courses: {
    key: 'courses',
    slug: 'courses',
    singular: 'Course',
    plural: 'Courses',
    route: '/admin/directory/courses',
    endpoint: DIRECTORY_ENDPOINTS.courses,
    icon: BookOpen,
    subnoteSuffix: 'published syllabus',
    fields: [
      { name: 'course_code', label: 'Course Code', type: 'text', required: true, placeholder: 'e.g. CHEM 201' },
      { name: 'course_name', label: 'Course Name', type: 'text', required: true, placeholder: 'Physical Chemistry I' },
      { name: 'department_id', label: 'Department', type: 'department_select', required: true },
      { name: 'lecturer_id', label: 'Lecturer in Charge', type: 'lecturer_select' },
      { name: 'credit_hours', label: 'Credit Hours', type: 'number', placeholder: '3' },
      { name: 'level', label: 'Level', type: 'select', options: ['100', '200', '300', '400'] },
      { name: 'semester', label: 'Semester', type: 'select', options: ['First Semester', 'Second Semester'] },
      { name: 'is_active', label: 'Status', type: 'boolean', default: true },
      { name: 'description', label: 'Course Description / Syllabus', type: 'textarea', colSpan: 2, placeholder: 'Course objectives, prerequisites, and laboratory topics...' },
    ],
  },

  clubs: {
    key: 'clubs',
    slug: 'clubs',
    singular: 'Club',
    plural: 'Clubs',
    route: '/admin/directory/clubs',
    endpoint: DIRECTORY_ENDPOINTS.clubs,
    icon: Compass,
    subnoteSuffix: 'active campus groups',
    imageField: 'logo_url',
    fields: [
      { name: 'logo_url', label: 'Club Logo', type: 'image', colSpan: 2 },
      { name: 'name', label: 'Club Name', type: 'text', required: true, placeholder: 'e.g. Chemical Society of Ghana - Student Chapter' },
      { name: 'acronym', label: 'Acronym', type: 'text', placeholder: 'e.g. CSG' },
      { name: 'category', label: 'Category', type: 'select', options: ['Academic', 'Professional', 'Research', 'Social', 'Outreach'] },
      { name: 'president', label: 'President / Leader', type: 'text', placeholder: 'Kofi Mensah' },
      { name: 'department_id', label: 'Affiliated Department', type: 'department_select' },
      { name: 'contact_email', label: 'Contact Email', type: 'email', placeholder: 'info@chemclub.org' },
      { name: 'contact_phone', label: 'Contact Phone', type: 'text', placeholder: '+233 55 444 3322' },
      { name: 'meeting_location', label: 'Meeting Location', type: 'text', placeholder: 'Science Library Seminar Rm 2' },
      { name: 'meeting_day', label: 'Meeting Day', type: 'select', options: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] },
      { name: 'meeting_time', label: 'Meeting Time', type: 'time' },
      { name: 'social_links', label: 'Social Media / Links', type: 'text', placeholder: 'https://instagram.com/chem_society' },
      { name: 'is_active', label: 'Status', type: 'boolean', default: true },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2, placeholder: 'Purpose, activities, and membership criteria...' },
    ],
  },

  committees: {
    key: 'committees',
    slug: 'committees',
    singular: 'Committee',
    plural: 'Committees',
    route: '/admin/directory/committees',
    endpoint: DIRECTORY_ENDPOINTS.committees,
    icon: Shield,
    subnoteSuffix: 'active assemblies',
    hasMembers: true,
    fields: [
      { name: 'name', label: 'Committee Name', type: 'text', required: true, placeholder: 'e.g. Departmental Curriculum & Exam Committee' },
      { name: 'chairperson', label: 'Chairperson', type: 'text', placeholder: 'Prof. Yaa Asantewaa' },
      { name: 'secretary', label: 'Secretary', type: 'text', placeholder: 'Dr. Ernest Boateng' },
      { name: 'academic_year', label: 'Academic Year', type: 'text', placeholder: '2025/2026' },
      { name: 'department_id', label: 'Department', type: 'department_select' },
      { name: 'contact_email', label: 'Contact Email', type: 'email', placeholder: 'curriculum@chem.ug.edu.gh' },
      { name: 'contact_phone', label: 'Contact Phone', type: 'text', placeholder: '+233 24 111 2233' },
      { name: 'is_active', label: 'Status', type: 'boolean', default: true },
      { name: 'purpose', label: 'Mandate & Purpose', type: 'textarea', colSpan: 2, placeholder: 'Terms of reference and committee scope...' },
      { name: 'description', label: 'Additional Details', type: 'textarea', colSpan: 2, placeholder: 'Meeting schedules and member criteria...' },
    ],
  },

  departments: {
    key: 'departments',
    slug: 'departments',
    singular: 'Department',
    plural: 'Departments',
    route: '/admin/directory/departments',
    endpoint: DIRECTORY_ENDPOINTS.departments,
    icon: Layers,
    subnoteSuffix: 'All active programs',
    fields: [
      { name: 'name', label: 'Department Name', type: 'text', required: true, placeholder: 'e.g. Department of Chemistry' },
      { name: 'code', label: 'Department Code', type: 'text', required: true, placeholder: 'e.g. CHEM' },
      { name: 'location', label: 'Building / Location', type: 'text', placeholder: 'Science Complex, Block B' },
      { name: 'email', label: 'General Email', type: 'email', placeholder: 'chemistry@ug.edu.gh' },
      { name: 'phone', label: 'Phone Number', type: 'text', placeholder: '+233 30 250 0123' },
      { name: 'website', label: 'Website', type: 'text', placeholder: 'https://chemistry.ug.edu.gh' },
      { name: 'is_active', label: 'Status', type: 'boolean', default: true },
      { name: 'description', label: 'Description', type: 'textarea', colSpan: 2, placeholder: 'Overview of academic programs, laboratories, and history...' },
    ],
  },

  contacts: {
    key: 'contacts',
    slug: 'contacts',
    singular: 'Contact',
    plural: 'Contacts',
    route: '/admin/directory/contacts',
    endpoint: DIRECTORY_ENDPOINTS.contacts,
    icon: Phone,
    subnoteSuffix: 'visible directory numbers',
    fields: [
      { name: 'name', label: 'Name / Office', type: 'text', required: true, placeholder: 'e.g. Chemistry Stores & Inventory' },
      { name: 'role', label: 'Role / Designation', type: 'text', placeholder: 'Laboratory Support Officer' },
      { name: 'category', label: 'Category', type: 'select', options: ['Administration', 'Academic Support', 'Emergency', 'Laboratory', 'Library', 'Student Services'] },
      { name: 'department', label: 'Department / Unit', type: 'text', placeholder: 'Chemistry Dept' },
      { name: 'office', label: 'Office / Room', type: 'text', placeholder: 'Room G-12, Ground Floor' },
      { name: 'location', label: 'Campus Location', type: 'text', placeholder: 'Main Science Annex' },
      { name: 'phone', label: 'Phone Number', type: 'text', placeholder: '+233 24 999 8888' },
      { name: 'email', label: 'Email', type: 'email', placeholder: 'stores@chem.ug.edu.gh' },
      { name: 'website', label: 'Website / Link', type: 'text', placeholder: 'https://chem.ug.edu.gh/stores' },
      { name: 'is_active', label: 'Status', type: 'boolean', default: true },
      { name: 'description', label: 'Notes / Operating Hours', type: 'textarea', colSpan: 2, placeholder: 'Available weekdays 8:30am - 4:30pm...' },
    ],
  },
}
